import BasePackage from '../';

export default class FlagPackage extends BasePackage {

    items = [
        { id: 1, image: require('./images/1.png') },
        { id: 2, image: require('./images/2.png') },
        { id: 3, image: require('./images/3.png') },
        { id: 4, image: require('./images/4.png') },
        { id: 5, image: require('./images/5.png') },
        { id: 6, image: require('./images/6.png') },
        { id: 7, image: require('./images/7.png') },
        { id: 8, image: require('./images/8.png') },
        { id: 9, image: require('./images/9.png') },
        { id: 10, image: require('./images/10.png') },
        { id: 11, image: require('./images/11.png') },
        { id: 12, image: require('./images/12.png') },
        { id: 13, image: require('./images/13.png') },
        { id: 14, image: require('./images/14.png') },
        { id: 15, image: require('./images/15.png') },
        { id: 16, image: require('./images/16.png') },
        { id: 17, image: require('./images/17.png') },
        { id: 18, image: require('./images/18.png') },
        { id: 19, image: require('./images/19.png') },
        { id: 20, image: require('./images/20.png') },
        { id: 21, image: require('./images/21.png') },
        { id: 22, image: require('./images/22.png') },
        { id: 23, image: require('./images/23.png') },
        { id: 24, image: require('./images/24.png') },
        { id: 25, image: require('./images/25.png') },
        { id: 26, image: require('./images/26.png') },
        { id: 27, image: require('./images/27.png') },
        { id: 28, image: require('./images/28.png') },
        { id: 29, image: require('./images/29.png') },
        { id: 30, image: require('./images/30.png') },
        { id: 31, image: require('./images/31.png') },
        { id: 32, image: require('./images/32.png') },
        { id: 33, image: require('./images/33.png') },
        { id: 34, image: require('./images/34.png') },
        { id: 35, image: require('./images/35.png') },
        { id: 36, image: require('./images/36.png') },
        { id: 37, image: require('./images/37.png') },
        { id: 38, image: require('./images/38.png') },
        { id: 39, image: require('./images/39.png') },
        { id: 40, image: require('./images/40.png') },
        { id: 41, image: require('./images/41.png') },
        { id: 42, image: require('./images/42.png') },
        { id: 43, image: require('./images/43.png') },
        { id: 44, image: require('./images/44.png') },
        { id: 45, image: require('./images/45.png') },
        { id: 46, image: require('./images/46.png') },
        { id: 47, image: require('./images/47.png') },
        { id: 48, image: require('./images/48.png') },
        { id: 49, image: require('./images/49.png') },
        { id: 50, image: require('./images/50.png') },
        { id: 51, image: require('./images/51.png') },
        { id: 52, image: require('./images/52.png') },
        { id: 53, image: require('./images/53.png') },
        { id: 54, image: require('./images/54.png') },
        { id: 55, image: require('./images/55.png') },
        { id: 56, image: require('./images/56.png') },
        { id: 57, image: require('./images/57.png') },
        { id: 58, image: require('./images/58.png') },
        { id: 59, image: require('./images/59.png') },
        { id: 60, image: require('./images/60.png') },
        { id: 61, image: require('./images/61.png') },
        { id: 62, image: require('./images/62.png') },
        { id: 63, image: require('./images/63.png') },
        { id: 64, image: require('./images/64.png') },
        { id: 65, image: require('./images/65.png') },
        { id: 66, image: require('./images/66.png') },
        { id: 67, image: require('./images/67.png') },
        { id: 68, image: require('./images/68.png') },
        { id: 69, image: require('./images/69.png') },
        { id: 70, image: require('./images/70.png') },
        { id: 71, image: require('./images/71.png') },
        { id: 72, image: require('./images/72.png') },
        { id: 73, image: require('./images/73.png') },
        { id: 74, image: require('./images/74.png') },
        { id: 75, image: require('./images/75.png') },
        { id: 76, image: require('./images/76.png') },
        { id: 77, image: require('./images/77.png') },
        { id: 78, image: require('./images/78.png') },
        { id: 79, image: require('./images/79.png') },
        { id: 80, image: require('./images/80.png') },
        { id: 81, image: require('./images/81.png') },
        { id: 82, image: require('./images/82.png') },
        { id: 83, image: require('./images/83.png') },
        { id: 84, image: require('./images/84.png') },
        { id: 85, image: require('./images/85.png') },
        { id: 86, image: require('./images/86.png') },
        { id: 87, image: require('./images/87.png') },
        { id: 88, image: require('./images/88.png') },
        { id: 89, image: require('./images/89.png') },
        { id: 90, image: require('./images/90.png') },
        { id: 91, image: require('./images/91.png') },
        { id: 92, image: require('./images/92.png') },
        { id: 93, image: require('./images/93.png') },
        { id: 94, image: require('./images/94.png') },
        { id: 95, image: require('./images/95.png') },
        { id: 96, image: require('./images/96.png') },
        { id: 97, image: require('./images/97.png') },
        { id: 98, image: require('./images/98.png') },
        { id: 99, image: require('./images/99.png') },
        { id: 100, image: require('./images/100.png') },
        { id: 101, image: require('./images/101.png') },
        { id: 102, image: require('./images/102.png') },
        { id: 103, image: require('./images/103.png') },
        { id: 104, image: require('./images/104.png') },
        { id: 105, image: require('./images/105.png') },
        { id: 106, image: require('./images/106.png') },
        { id: 107, image: require('./images/107.png') },
        { id: 108, image: require('./images/108.png') },
        { id: 109, image: require('./images/109.png') },
        { id: 110, image: require('./images/110.png') },
    ];

    constructor() {
        super();
        this.randomImages(40);
    }
}
